version: "3.4"

name: chomp-db
services:
  chomp.db:
    image: postgis/postgis:16-master
    container_name: chomp-db
    environment:
      - POSTGRES_DB=chomp-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: >
      -c max_connections=1000
