export const TRACKING_EVENTS = {
  WALLET_CONNECTED: "LoginWalletConnected",
  CLAIM_STARTED: "ClaimStarted",
  CLAIM_FAILED: "ClaimFailed",
  CLAIM_SUCCEEDED: "ClaimSucceeded",
  REVEAL_SUCCEEDED: "RevealSucceeded",
  REVEAL_DIALOG_CLOSED: "RevealDialogClosed",
  REVEAL_DIALOG_OPENED: "RevealDialogOpened",
  REVEAL_DIALOG_LOADED: "RevealDialogLoaded",
  REVEAL_STARTED: "RevealStarted",
  REVEAL_TRANSACTION_SIGNED: "RevealTransactionSigned",
  REVEAL_TRANSACTION_CANCELLED: "RevealTransactionCancelled",
  REVEAL_FAILED: "RevealFailed",
  LOGIN_STARTED: "LoginStarted",
  Login_Wallet_Selected: "LoginWalletSelected",
  Login_Email_Submitted: "LoginEmailSubmitted",
  LOGIN_FAILED: "LoginFailed",
  LOGIN_SUCCEED: "LoginSucceed",
  DECK_STARTED: "DeckStarted",
  QUESTION_LOADED: "QuestionLoaded",
  FIRST_ORDER_SELECTED: "QuestionFirstOrderAnswerSelected",
  SECOND_ORDER_SELECTED: "QuestionSecondOrderAnswerSelected",
  QUESTION_ANSWERED_SUCCEEDED: "QuestionAnsweredSucceeded",
  QUESTION_ANSWERED_FAILED: "QuestionAnsweredFailed",
  DECK_COMPLETED: "DeckCompletionSucceeded",
  SHARE_EARN_URL: "ShareTaskonURL",
  HOME_STAT_CARD_DIALOG_OPENED: "HomeStatCardDialogOpened",
  HOME_STAT_CARD_DIALOG_CLOSED: "HomeStatCardDialogClosed",
  PAGE_VIEW: "PageView",
  WELCOME_BACK_ANSWER_BUTTON_CLICKED: "WelcomeBackAnswerButtonClicked",
  WELCOME_BACK_REVEAL_BUTTON_CLICKED: "WelcomeBackRevealButtonClicked",
  DECK_CLICKED: "DeckClicked",
  SHARE_ALL_DIALOG_LOADED: "ShareAllDialogLoaded",
  SHARE_DIALOG_LOADED: "ShareDialogLoaded",
  SHARE_ALL_DIALOG_CLOSED: "ShareAllDialogClosed",
  SHARE_DIALOG_CLOSED: "ShareDialogClosed",
  SHARE_ALL_X_BUTTON_CLICKED: "ShareAllXButtonClicked",
  SHARE_X_BUTTON_CLICKED: "ShareXButtonClicked",
  SHARE_BUTTON_CLICKED: "ShareButtonClicked",
  TELEGRAM_USER_MINIAPP_OPENED: "TelegramUserMiniAppOpened",
  MYSTERY_BOX_DIALOG_OPENED: "MysteryBoxDialogOpened",
  MYSTERY_BOX_DIALOG_CLOSED: "MysteryBoxDialogClosed",
  MYSTERY_BOX_OPENED: "MysteryBoxOpened",
  MYSTERY_BOX_SKIPPED: "MysteryBoxSkipped",
} as const;

export const TRACKING_METADATA = {
  REVEAL_TYPE: "RevealType",
  USER_WALLET_ADDRESS: "UserWalletAddress",
  USER_EMAIL: "UserEmail",
  USERNAME: "Username",
  USER_ID: "UserId",
  QUESTION_ID: "QuestionId",
  QUESTION_TEXT: "QuestionText",
  QUESTION_ANSWER_OPTIONS: "QuestionAnswerOptions",
  QUESTION_ANSWER_SELECTED: "QuestionAnswerSelected",
  QUESTION_ANSWER_SELECTED_PERCENTAGE: "QuestionAnswerSelectedPercentage",
  QUESTION_HAS_IMAGE: "QuestionHasImage",
  TRANSACTION_SIGNATURE: "TransactionSignature",
  CLAIMED_AMOUNT: "ClaimedAmount",
  REVEAL_DIALOG_TYPE: "RevealDialogType",
  LOGIN_FAILED_REASON: "LoginFailed",
  CONNECTOR_NAME: "ConnectorName",
  DECK_ID: "DeckId",
  DECK_NAME: "DeckName",
  IS_DAILY_DECK: "IsDailyDeck",
  TYPE: "Type",
  SOURCE: "Source",
  ANSWER_TAB: "AnswerTab",
  URL_PATH: "UrlPath",
  URL_SEARCH: "UrlSearch",
  TELEGRAM_ID: "TelegramId",
  TELEGRAM_FIRST_NAME: "TelegramFirstName",
  TELEGRAM_LAST_NAME: "TelegramLastName",
  TELEGRAM_USERNAME: "TelegramUsername",
};

export const HOME_STAT_CARD_TYPE = {
  STREAK: "Streak",
  BONK_CLAIMED: "BonkClaimed",
  CREDITS_EARNED: "CreditsEarned",
  POINTS_EARNED: "PointsEarned",
};

export const REVEAL_TYPE = {
  SINGLE: "Single",
  ALL: "All",
};

export const REVEAL_DIALOG_TYPE = {
  REVEAL_OR_CLOSE: "RevealOrClose",
  INSUFFICIENT_FUNDS: "InsufficientFunds",
};

export type TrackingEventsType = keyof typeof TRACKING_EVENTS;
